format = """
[$os](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
[](fg:#4C566A bg:#8FBCBB)\
[](fg:#8FBCBB bg:#D8DEE9)\
[ ](fg:#D8DEE9)\
$git_branch\
$git_status\
$python
[\n$character ](fg:#33658A)\
"""
command_timeout = 5000

[os]
disabled = false
style = "bg:#434C5E"

[os.symbols]
Fedora = " "

[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documentos" = "󰈙"
"Descargas" = ""
"UNAM" = "󰑴"
"Imágenes" = ""

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)$path'

[git_branch]
symbol = ""
style = "fg:#B48EAD"
format = '[$symbol on $branch]($style)'

[git_status]
style = "fg:#B48EAD"
format = '( [$all_status$ahead_behind]($style)) '

[python]
symbol = " "
style = "fg:#EBCB8B"
format = ' [${symbol}${pyenv_prefix}(\($virtualenv\))]($style)'

[character]
disabled = false
success_symbol = '[ ](bold fg:#8FBCBB)'
error_symbol = '[ ](bold fg:#BF616A)'
